### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by FedericoCeratto** [webwurst/chattle#3]
OrderedDict is not available in Python 2.6 - could you add a try/except block around the import statement and provide an alternative implementation of it? Thanks

**Comment by webwurst** [comment]
You are right, guess this could help:
http://pypi.python.org/pypi/ordereddict/1.1

I want to use ordered dicts, so a conversion of a json document to dict and back still looks the same.

**Comment by FedericoCeratto** [comment]
Python 2.6 is obsolete - closing bug.
